export const threadAction = {
  FETCH_THREAD_REQUEST: "FETCH_THREAD_REQUEST",
  FETCH_THREAD_SUCCESS: "FETCH_THREAD_SUCCESS",
  FETCH_THREAD_FAILURE: "FETCH_THREAD_FAILURE",
  ACCEPT_THREAD_REQUEST: "ACCEPT_THREAD_REQUEST",
  ACCEPT_THREAD_SUCCESS: "ACCEPT_THREAD_SUCCESS",
  ACCEPT_THREAD_FAILURE: "ACCEPT_THREAD_FAILURE",
};
